### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dineshrboson** [chrissunny94/ackerman_ros_robot_gazebo_simulation#2]
![Screenshot from 2021-06-04 00-37-27](https://user-images.githubusercontent.com/77951479/120698864-403cd380-c4cd-11eb-955d-e336d5698f33.png)
![Screenshot from 2021-06-04 00-37-41](https://user-images.githubusercontent.com/77951479/120698870-43d05a80-c4cd-11eb-9ad3-283cbc7cb991.png)

**Comment by dineshrboson** [comment]
Ros melodic 
Gazebo -9

**Comment by chrissunny94** [comment]
Yes i am aware of these issues . I am working on  reducing it to a single launch file  or not more than 2 .

I will push them soon .

**Comment by dineshrboson** [comment]
roslaunch rbcar_sim_bringup rbcar_complete.launch
this launch command gave me the errors
and the remaining launch commands work fine but the cmd_vel and ackrramanncmd are not publishing to the vehicle.

**Comment by tomlogan501** [comment]
Hi @chrissunny94  @dineshrboson 
I also try to make this project work on melodic inside a VM.
BTW did you implement the ackermann controller or one of your own design ?

**Comment by chrissunny94** [comment]
@tomlogan501 
[I am porting it to noetic ,](https://github.com/chrissunny94/ackerman_ros_robot_gazebo_simulation/tree/noetic)

For ackerman 

- This script interfaces with gazebo and controls the simulated bot  https://github.com/chrissunny94/ackerman_ros_robot_gazebo_simulation/blob/master/custom_controllers/ackermann-drive-teleop/scripts/joyop.py
- I am using TEB plugin with move_base for the navigation part .

**Comment by dineshrboson** [comment]
Will it work in melodic ?

**Comment by chrissunny94** [comment]
It should work with melodic also , i havent tested it though .

**Comment by dineshrboson** [comment]
yeah okay like I raised an issue with the ros melodic execution, I thought you committed after updating with the working code.

**Comment by chrissunny94** [comment]
will probably adapt this code 


for current ROS2 

As for this issue i am closing it as i just merged the noetic branch to master .
