### ISSUE TITLE
Robot moves very slow in simulation (issue with URDF)

### ISSUE THREAD

**Issue by KoushikRaghav** [chrissunny94/ackerman_ros_robot_gazebo_simulation#3]
Tried implementing teb local planner in ackermann steering robot. The robot moves very slow (very small linear x value) compared to diff drive

**Comment by chrissunny94** [comment]
I have noticed this issue , i am not sure what was going wrong . 

I think it has something to do with the URDF modelling . I think the weight of the Robot was too much or something like that . 

Do feel free to make a PR if you find a solution
